---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
            defaultZone: http://localhost:8010/eureka/
      
---
spring:
  profiles: subject
words: I,You,He,She,It
  
---
spring:
  profiles: verb
words: ran,knew,had,saw,bought,destroyed

---
spring:
  profiles: article
words: a,the,an

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely,tiny,southamerican,extra

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog,car,truck,bicycle,computer,pen,ipad
  
